### ISSUE TITLE
Bug - Error occurs if a Body with a Revolute Constraint is destroyed

### ISSUE THREAD

**Issue by hdodov** [photonstorm/phaser#2843]
My Phaser version is 2.6.2.
I have two Bodies with a Revolute Constraint on them.

````
this.constraint = game.physics.p2.createRevoluteConstraint(
	mySprite.body, [this.x, this.y],
	this.spr.body, [0, 0]
);
````
When I destroy one or the other, I get the following error:
```
phaser.min.js:6 Uncaught TypeError: Cannot read property 'neighbors' of undefined
    at d.split (http://localhost/js/phaser.min.js:6:10417)
    at d.internalStep (http://localhost/js/phaser.min.js:6:17447)
    at d.step (http://localhost/js/phaser.min.js:6:14618)
    at c.Physics.P2.update (http://localhost/js/phaser.min.js:24:14311)
    at c.Physics.update (http://localhost/js/phaser.min.js:23:6484)
    at c.Game.updateLogic (http://localhost/js/phaser.min.js:12:5240)
    at c.Game.update (http://localhost/js/phaser.min.js:12:4563)
    at c.RequestAnimationFrame.updateRAF (http://localhost/js/phaser.min.js:18:10004)
    at window.requestAnimationFrame.forceSetTimeOut._onLoop (http://localhost/js/phaser.min.js:18:9880)
```
However, if I do this:
````
game.physics.p2.removeConstraint(this.constraint);
this.spr.destroy();
````
Everything is working fine.

My suggestion is to modify the `destroy()` method of the P2 Body in such a way that it checks whether it participates in a Constraint and removes it, if it does.

**Comment by photonstorm** [comment]
Thank you for taking the time to open this issue. However, official support for Phaser 2 has now ended as we focus on preparing Phaser 3 for beta release. In a bid to keep the project tidy, and avoid confusion, we are closing all v2 related issues.

This does not mean your issue won't be looked-at. In November 2016 the [Phaser CE (Community Edition)](https://github.com/photonstorm/phaser-ce) project began. The aim of Phaser CE was to allow the community to continue v2 development. Since then it has gained significant traction, with many updates and releases.

If you are still interested in having your issue investigated we strongly recommend testing the latest Phaser CE release. And only if the problem persists, opening an issue on the Phaser CE repo.
