### ISSUE TITLE
[BUG?] Object.prototype.* breaks Phaser.Game when using Phaser.AUTO

### ISSUE THREAD

**Issue by Blue-EyesWhiteDragon** [photonstorm/phaser#2849]
The following error comes up on Chrome (v 54 Stable)
```
phaser.js:16588 Uncaught TypeError: Cannot read property 'call' of undefined
    at PIXI.PixiShader.syncUniforms (http://127.0.0.1:8887/assets/js/phaser.js:16588:31)
    at PIXI.WebGLSpriteBatch.flush (http://127.0.0.1:8887/assets/js/phaser.js:18843:28)
    at PIXI.WebGLSpriteBatch.end (http://127.0.0.1:8887/assets/js/phaser.js:18456:10)
    at PIXI.WebGLRenderer.renderDisplayObject (http://127.0.0.1:8887/assets/js/phaser.js:17503:22)
    at PIXI.WebGLRenderer.render (http://127.0.0.1:8887/assets/js/phaser.js:17466:10)
    at Phaser.Game.updateRender (http://127.0.0.1:8887/assets/js/phaser.js:36387:27)
    at Phaser.Game.update (http://127.0.0.1:8887/assets/js/phaser.js:36229:18)
    at Phaser.RequestAnimationFrame.updateRAF (http://127.0.0.1:8887/assets/js/phaser.js:61979:23)
    at _onLoop (http://127.0.0.1:8887/assets/js/phaser.js:61962:30)
```

HTML: 

```
<body>
    <div id="site">
        <div class="container">
            <header id="header" class="row">
                <h1>Game</h1>
            </header>
            <div id="wrapper" class="row"></div>
            <div class="row">
                <a class="small wide button orange" tabindex="0">Woo</a>
            </div>
            <footer id="footer" class="row">&copy; 2016 | MIT License</footer>
        </div>
    </div>
    <div id="scripts">
        <script>Object.prototype.something=function(){};</script> <!--// this is what breaks phaser for some reason -->
        <script type="text/javascript" src="assets/js/phaser.js"></script>
        <script type="text/javascript" src="assets/js/game.js"></script>
    </div>
</body>
```

`game.js`

```
window.addEventListener("load", function () {
    
    "use strict";
    
    if ( typeof Phaser === "undefined" || typeof Phaser === null ) {
        throw Error("This game requires Phaser v2.6.2 (Kore Springs)!");
    }
    
    var canvas,
        game,
        dimensions = {
            width : ((16*32)/4)*4,
            height : ((16*32)/4)*3
        },
        
        init = function () {
            game = new Phaser.Game(
                dimensions.width,
                dimensions.height,
                Phaser.AUTO,
                "wrapper",
                { preload : preload, create : create, update : update, render : render },
                true
            );
        }
    ;
    
    init();
    
    function preload () {
        
    }
    
    function create () {
        
    }
    
    function update () {
        
    }
    
    function render () {
        
    }
    
});
```

Adding any property to the the `Object.prototype` breaks Phaser when it tries to run `Phaser.Game` with Phaser.WEBGL (which is the result of using Phaser.AUTO a good majority of the time)... curious.

**Comment by photonstorm** [comment]
You've added a function to _every single_ object Phaser and Pixi (and JS in general) creates. There are several places where objects are iterated (such as in `syncUniforms`), and the iteration is expecting a properly formed local object, which it no longer has because it's gained a random new function on its prototype.

I guess technically `syncUniforms` could do a `hasOwnProperty` check on its object to avoid this, but it's a _very_ hot method, and adding that overhead for all properties in the object, 60 times per second, is less than desirable. Feel free to patch that in, in your own fork of the repo, but personally I'd find a less destructive way of doing whatever it is you're trying to do.

**Comment by Blue-EyesWhiteDragon** [comment]
RIght, thanks for the info!
