### ISSUE TITLE
ReferenceError: WebGLTexture is not defined (3.19.0; HEADLESS)

### ISSUE THREAD

**Issue by tsphillips** [photonstorm/phaser#4711]
## Version

* Phaser Version: 3.19.0

* Operating system: MacOS Mojave 10.14.5

* Browser: N/A

* Node: v12.8.0

## Description

Running Phaser 3.19.0 in HEADLESS mode produces:

Error: Uncaught [ReferenceError: WebGLTexture is not defined]

## Example Test Code

```
const config = {
    type: Phaser.HEADLESS,
    autoFocus: false,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    physics: {
        default: 'arcade',
        arcade: {
            debug: false,
            gravity: { y: 0 }
        }
    },
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

function preload() {}
function create() {}
function update() {}

const game = new Phaser.Game(config);
```

## Additional Information

Works without errors or warnings using version 3.18.0.

Version 3.19.0 produces the WebGLTexture error. (https://cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.min.js)

Full error message:
```
dunwich:rotg flip$ node --inspect server/server.js 
Debugger listening on ws://127.0.0.1:9229/30fd6358-4aff-41fe-9023-fa61354a9d2e
For help, see: https://nodejs.org/en/docs/inspector
%c %c %c %c %c Phaser v3.19.0 (Headless | HTML5 Audio) %c https://phaser.io background: #ff0000 background: #ffff00 background: #00ff00 background: #00ffff color: #ffffff; background: #000000 background: #fff
Error: Uncaught [ReferenceError: WebGLTexture is not defined]
    at reportException (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at innerInvokeEventListeners (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
    at invokeEventListeners (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
    at HTMLImageElementImpl._dispatch (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
    at fireAnEvent (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
    at /Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:57:13
    at processTicksAndRejections (internal/process/task_queues.js:85:5) ReferenceError: WebGLTexture is not defined
    at new initialize (https://cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.min.js:1:376530)
    at new initialize (https://cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.min.js:1:154373)
    at initialize.create (https://cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.min.js:1:370961)
    at HTMLImageElement.n.onload (https://cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.min.js:1:368018)
    at HTMLImageElement.<anonymous> (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at innerInvokeEventListeners (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
    at invokeEventListeners (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
    at HTMLImageElementImpl._dispatch (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
    at fireAnEvent (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
    at /Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:57:13
Error: Uncaught [ReferenceError: WebGLTexture is not defined]
    at reportException (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at innerInvokeEventListeners (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
    at invokeEventListeners (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
    at HTMLImageElementImpl._dispatch (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
    at fireAnEvent (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
    at /Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:57:13
    at processTicksAndRejections (internal/process/task_queues.js:85:5) ReferenceError: WebGLTexture is not defined
    at new initialize (https://cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.min.js:1:376530)
    at new initialize (https://cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.min.js:1:154373)
    at initialize.create (https://cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.min.js:1:370961)
    at HTMLImageElement.n.onload (https://cdn.jsdelivr.net/npm/phaser@3.19.0/dist/phaser.min.js:1:368018)
    at HTMLImageElement.<anonymous> (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at innerInvokeEventListeners (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
    at invokeEventListeners (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
    at HTMLImageElementImpl._dispatch (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
    at fireAnEvent (/Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
    at /Users/flip/Documents/Development/rotg/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:57:13
```

**Comment by tsphillips** [comment]
It looks like the offending line is TextureSource.js:150. The new 3.19 unconditionally references WebGLTexture:

```
        /**
         * Is the source image a WebGLTexture?
         *
         * @name Phaser.Textures.TextureSource#isGLTexture
         * @type {boolean}
         * @since 3.19.0
         */
        this.isGLTexture = (source instanceof WebGLTexture);
```

The old 3.18 was:

```
        /**
         * The WebGL Texture of the source image.
         *
         * @name Phaser.Textures.TextureSource#glTexture
         * @type {?WebGLTexture}
         * @default null
         * @since 3.0.0
         */
        this.glTexture = null;
```
I have not explored the internals of Phaser 3, so I don't know why this change was made. Maybe a Phaser shim for WebGLTexture or other display references would be appropriate if in HEADLESS mode? Or maybe there is a shim library for Node JS?

**Comment by tsphillips** [comment]
These seem to work as shims for WebGLTexture:

ES5:
`function WebGLTexture() { }`

ES6:
`WebGLTexture = class { }`

For example:

```
const config = {
    type: Phaser.HEADLESS,
    autoFocus: false,
    parent: 'phaser-example',
    width: 800,
    height: 600,
    physics: {
        default: 'arcade',
        arcade: {
            debug: false,
            gravity: { y: 0 }
        }
    },
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

function preload() {}
function create() {}
function update() {}

function WebGLTexture() { } // shim for Phaser 3.19.0, using ES5
// WebGLTexture = class { } // shim for Phaser 3.19.0, using ES6

const game = new Phaser.Game(config);
```

jsdom provides a shim for HTMLCanvasElement, which is why the following code does not cause problems in a HEADLESS environment:

```
        /**
         * Is the source image a Canvas Element?
         *
         * @name Phaser.Textures.TextureSource#isCanvas
         * @type {boolean}
         * @since 3.0.0
         */
        this.isCanvas = (source instanceof HTMLCanvasElement);
```

**Comment by photonstorm** [comment]
I assume the following should work as well?

`this.isGLTexture = (window.hasOwnProperty('WebGLTexture') && source instanceof WebGLTexture);`
