### ISSUE TITLE
Spine build script doesn't work

### ISSUE THREAD

**Issue by RollinSafary** [photonstorm/phaser#5243]
Here is the error
```
ERROR in ./runtimes/spine-both.js
.../node_modules/phaser/node_modules/exports-loader/dist/cjs.js):
ValidationError: Invalid options object. Exports Loader has been initialized using an options object that does not match the API schema.
 - options misses the property 'exports'. Should be:
   non-empty string | object { name, syntax?, alias? } | [non-empty string | object { name, syntax?, alias? }, ...] (should not have fewer than 1 item)
    at validate (...node_modules\phaser\node_modules\schema-utils\dist\validate.js:96:11)
    at Object.loader (...\node_modules\phaser\node_modules\exports-loader\dist\index.js:28:28)
 @ ./SpinePlugin.js 12:12-28
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
