### ISSUE TITLE
navigator is not defined in node environment

### ISSUE THREAD

**Issue by quentincaffeino** [photonstorm/phaser#5736]
## Version

* Phaser Version: 3.55.2

* Operating system: Linux bosh-smart-toster 5.9.10-050910-generic #202011221708 SMP Sun Nov 22 18:07:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

## Description

```
navigator is not defined

ReferenceError: navigator is not defined
    at init (./test/node_modules/.pnpm/phaser@3.55.2/node_modules/phaser/src/device/OS.js:69:14)
    at Object.<anonymous> (./test/node_modules/.pnpm/phaser@3.55.2/node_modules/phaser/src/device/OS.js:186:18)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (./test/node_modules/.pnpm/phaser@3.55.2/node_modules/phaser/src/device/index.js:32:9)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
```

## Additional Information

I'm running a website with ssr and that means that website code is run on the backend in node env where navigator object does not exist. I see two solutions:
1. Initialize OS.js inside Phaser initialization (not before it).
2. Check if it is a node env first, otherwise try if navigator exists first before accessing it.

**Comment by quentincaffeino** [comment]
Ok I've tried fixing it and it seems that browser calls are made from everywhere in code, doesn't really seem fixable.

**Comment by photonstorm** [comment]
v3 was really never intended to be run on the server. As you've found it, once you solve OS, you've got loads of other places to cover - from Input, to the Scale Manager, to even the Time Step. It's a very non-trivial task and I'm not sure you'd even have something working at the end of it.

**Comment by quentincaffeino** [comment]
Thank you for responding. Problem is I don't want to run it on server, it is ran automatically when I import it. But yeah, that would be a very tedious work.

**Comment by quentincaffeino** [comment]
For the future generations: I've found a solution and it was pretty easy. The solution was to lazy load the game component.

Here's a code I've come up with svelte kit:

```svelte
<script>
  import { onMount } from "svelte";

  let gameComponent;

  onMount(async () => {
    gameComponent = (await import("$lib/Game.svelte")).default;
  });
</script>

{#if gameComponent}
  <svelte:component this={gameComponent} />
{/if}
```
